CREATE TABLE IF NOT EXISTS Bifrost_site_table (
    auto_id INT AUTO_INCREMENT PRIMARY KEY,
    batch_id INT NOT NULL,
    Asset VARCHAR(255),
    Value DECIMAL(20,3),
    tvl DECIMAL(20,6),
    tvm DECIMAL(20,6),
    holders INT,
    apy DECIMAL(20,6),
    apyBase DECIMAL(20,6),
    apyReward DECIMAL(20,6),
    totalIssuance DECIMAL(20,6),
    holdersList TEXT,
    annualized_income DECIMAL(20,6),
    bifrost_staking_7day_apy DECIMAL(20,6),
    created DATETIME,
    daily_reward DECIMAL(20,6),
    exited_node INT,
    exited_not_transferred_node INT,
    exiting_online_node INT,
    gas_fee_income DECIMAL(20,6),
    id INT,
    mev_7day_apy DECIMAL(20,6),
    mev_apy DECIMAL(20,6),
    mev_income DECIMAL(20,6),
    online_node INT,
    slash_balance DECIMAL(20,6),
    slash_num INT,
    staking_apy DECIMAL(20,6),
    staking_income DECIMAL(20,6),
    total_apy DECIMAL(20,6),
    total_balance DECIMAL(20,6),
    total_effective_balance DECIMAL(20,6),
    total_node INT,
    total_reward DECIMAL(20,6),
    total_withdrawals DECIMAL(20,6),
    stakingApy DECIMAL(20,6),
    stakingIncome DECIMAL(20,6),
    mevApy DECIMAL(20,6),
    mevIncome DECIMAL(20,6),
    gasFeeApy DECIMAL(20,6),
    gasFeeIncome DECIMAL(20,6),
    totalApy DECIMAL(20,6),
    totalIncome DECIMAL(20,6),
    baseApy DECIMAL(20,6),
    farmingAPY DECIMAL(20,6),
    veth2TVS DECIMAL(20,6),
    apyMev DECIMAL(20,6),
    apyGas DECIMAL(20,6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Bifrost_staking_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_id INT NOT NULL,
    contractAddress VARCHAR(255),
    symbol VARCHAR(50),
    slug VARCHAR(100),
    baseSlug VARCHAR(100),
    unstakingTime INT,
    users INT,
    apr DECIMAL(20,6),
    fee DECIMAL(20,6),
    price DECIMAL(20,6),
    exchangeRatio DECIMAL(20,6),
    supply DECIMAL(20,6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Bifrost_batchID_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_id INT NOT NULL,
    chain VARCHAR(25),
    status VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
