CREATE TABLE IF NOT EXISTS pool_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batch_id INT NOT NULL,
    pool_id VARCHAR(255),
    token0_id VARCHAR(255),
    token0_symbol VARCHAR(50),
    token0_name VARCHAR(255),
    token0_decimals INT,
    token1_id VARCHAR(255),
    token1_symbol VARCHAR(50),
    token1_name VARCHAR(255),
    token1_decimals INT,
    liquidity DOUBLE,
    sqrt_price DOUBLE,
    tick INT,
    volume_usd_current DOUBLE,
    volume_usd_24h_ago DOUBLE,
    volume_usd_24h DOUBLE,
    tx_count INT,
    fees_usd_current DOUBLE,
    fees_usd_24h_ago DOUBLE,
    fees_usd_24h DOUBLE,
    amount_token0 DOUBLE,
    amount_token1 DOUBLE,
    pools_apr DOUBLE,
    farming_apr DOUBLE,
    final_apr DOUBLE,
    token_rewards TEXT,
    timestamp VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
